### PR TITLE
Made changes to binary genome tree and genome tree client

### PR DESCRIPTION
**Pull request by Descartes90**

### CODE REVIEW

**Comment by jpcanty87** [comment]
👀

**Comment by jpcanty87** [comment]
Hey @Descartes90 Sorry for the late review. 

I can only see one commit still in this pull request. And also I don't see any changes in master.
Let's set up time tomorrow in order to pair on this.

the following commands should allow you to push to this branch

git add .
git commit -m "Your commit message"
git push origin **JJ-3**

**Comment by Descartes90** [comment]
I created JJ-4 because I thought its best to checkout a new branch for each push? (I remember hearing that), and I didn't push to master because I thought that was bad practice.    On Wednesday, July 24, 2019, 12:13:04 AM CDT, Jelani Canty <notifications@github.com> wrote:  
 
 
Hey @Descartes90 Sorry for the late review.

I can only see one commit still in this pull request. And also I don't see any changes in master.
Let's set up time tomorrow in order to pair on this.

the following commands should allow you to push to this branch

git add .
git commit -m "Your commit message"
git push origin JJ-3

**Comment by jpcanty87** [comment]
Did you push to JJ-4? Another pull request should have opened up. Lets meet at 7 virtually on Friday

**Comment by Descartes90** [comment]
I did push to JJ-4. I wrote git push origin JJ-4. Ok for Friday.
    On Wednesday, July 24, 2019, 11:56:19 PM CDT, Jelani Canty <notifications@github.com> wrote:  
 
 
Did you push to JJ-4? Another pull request should have opened up. Lets meet at 7 virtually on Friday

**Pull request merged**
